apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  config.yaml: |
    ---
    server_url: https://{{ .Values.domain }}
    listen_addr: {{ .Values.listen_addr }}
    metrics_listen_addr: {{ .Values.metrics_listen_addr }}
    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    ip_prefixes:
      - 100.64.0.0/10
    disable_check_updates: true
    db_type: sqlite3
    db_path: /var/lib/headscale/db.sqlite
    tls_cert_path: ""
    tls_key_path: ""
    log:
      format: text
      level: debug
    dns_config:
      override_local_dns: true
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      magic_dns: true
      base_domain: {{ .Values.baseDomain }}
    logtail:
      enabled: false

    oidc:
      only_start_if_oidc_is_available: false
      issuer: {{ .Values.oidc.issuer }}
      client_id: {{ .Values.oidc.client_id }}
      client_secret: {{ .Values.oidc.client_secret }} 
      scope: {{ .Values.oidc.scope }}

      # Alternatively, set `client_secret_path` to read the secret from the file.
      # It resolves environment variables, making integration to systemd's
      # `LoadCredential` straightforward:
      # client_secret_path: "${CREDENTIALS_DIRECTORY}/oidc_client_secret"
      # client_secret and client_secret_path are mutually exclusive.
      
      expiry: 180d
      use_expiry_from_token: false

      extra_params:
        domain_hint: buildstars.online
      # allowed_domains:
      #   - example.com
      # # Note: Groups from keycloak have a leading '/'
      # allowed_groups:
      #   - /headscale
      # allowed_users:
      #   - alice@example.com
      # strip_email_domain: true
