apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  config.yaml: |
    ---
    server_url: {{ .Values.server_url }}
    listen_addr: {{ .Values.listen_addr }}
    metrics_listen_addr: {{ .Values.metrics_listen_addr }}
    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    ip_prefixes:
      - 100.64.0.0/10
    disable_check_updates: true
    db_type: sqlite3
    db_path: /var/lib/headscale/db.sqlite
    tls_cert_path: ""
    tls_key_path: ""
    log:
      format: text
      level: debug
    dns_config:
      override_local_dns: true
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      magic_dns: true
      base_domain: buildstar.online
    logtail:
      enabled: false

