{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: milliner-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "headscale.buildstar.online"
      secretName: headscale-tls
  rules:
  - host: "headscale.buildstar.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: milliner-service
            port:
              number: 3030
{{- end }}
