{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: milliner-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
      proxy_pass http://85.10.207.22:3030;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_set_header Host $server_name;
          proxy_redirect http:// https://;
          proxy_buffering off;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
          add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "headscale.buildstar.online"
      secretName: headscale-tls
  rules:
  - host: "headscale.buildstar.online"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: milliner-service
            port:
              number: 3030
{{- end }}
