apiVersion: v1
kind: Service
metadata:
  name: headscale-server
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serverService.type }}
  ports:
    - port: {{ .Values.serverService.port }}
      targetPort: 8080
      protocol: TCP
      name: server
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: headscale-metrics
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - port:  {{ .Values.metricsService.port }}
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "headscale.selectorLabels" . | nindent 4 }}
