apiVersion: v1
kind: Service
metadata:
  name: headscale-server-service
spec:
  selector:
    app.kubernetes.io/name: headscale
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: headscale-server
---
apiVersion: v1
kind: Service
metadata:
  name: milliner-service
spec:
  selector:
    app.kubernetes.io/name: headscale
  type: LoadBalancer
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
      name: milliner-server
---
apiVersion: v1
kind: Service
metadata:
  name: headscale-metrics-service
spec:
  selector:
    app.kubernetes.io/name: headscale
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
