apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
data:
  config.yaml: |
    ---
    server_url: {{ .Values.server_url }}
    listen_addr: {{ .Values.listen_addr }}
    metrics_listen_addr: {{ .Values.metrics_listen_addr }}
    grpc_listen_addr: {{ .Values.grpc_listen_addr }}
    grpc_allow_insecure: {{ .Values.grpc_allow_insecure }}
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    ip_prefixes:
      - fd7a:115c:a1e0::/48
      - 100.64.0.0/10
    derp:
      server:
        enabled: false
        region_id: 999
        region_code: "headscale"
        region_name: "Headscale Embedded DERP"
        stun_listen_addr: "0.0.0.0:3478"
        private_key_path: /var/lib/headscale/derp_server_private.key
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      paths: []
      auto_update_enabled: true
      update_frequency: 24h
    disable_check_updates: false
    ephemeral_node_inactivity_timeout: 30m
    node_update_check_interval: 10s
    db_type: sqlite3
    db_path: /var/lib/headscale/db.sqlite
    # # Postgres config
    # If using a Unix socket to connect to Postgres, set the socket path in the 'host' field and leave 'port' blank.
    # db_type: postgres
    # db_host: localhost
    # db_port: 5432
    # db_name: headscale
    # db_user: foo
    # db_pass: bar
    # db_ssl: false
    acme_url: https://acme-v02.api.letsencrypt.org/directory
    acme_email: ""
    tls_letsencrypt_hostname: ""
    tls_letsencrypt_cache_dir: /var/lib/headscale/cache
    tls_letsencrypt_challenge_type: HTTP-01
    tls_letsencrypt_listen: ":http"
    tls_cert_path: ""
    tls_key_path: ""
    log:
      format: text
      level: info
    acl_policy_path: ""
    dns_config:
      override_local_dns: true
      nameservers:
        - 1.1.1.1
      domains: []
      # extra_records:
      #   - name: "grafana.myvpn.example.com"
      #     type: "A"
      #     value: "100.64.0.3"
      magic_dns: true
      base_domain: {{ .Values.base_domain }}
    unix_socket: /var/run/headscale/headscale.sock
    unix_socket_permission: "0770"
    # oidc:
    #   only_start_if_oidc_is_available: true
    #   issuer: "https://your-oidc.issuer.com/path"
    #   client_id: "your-oidc-client-id"
    #   client_secret: "your-oidc-client-secret"
    #   client_secret_path: "${CREDENTIALS_DIRECTORY}/oidc_client_secret"
    #   expiry: 180d
    #   use_expiry_from_token: false
    #   scope: ["openid", "profile", "email", "custom"]
    #   extra_params:
    #     domain_hint: example.com
    #   allowed_domains:
    #     - example.com
    #   allowed_groups:
    #     - /headscale
    #   allowed_users:
    #     - alice@example.com
    #   user: `first-name.last-name.example.com`
    #   strip_email_domain: true
    logtail:
      enabled: false
    randomize_client_port: false

